### POWER OPTIONS
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=10800000
CONFIG_ZMK_IDLE_TIMEOUT=300000

# Glidepoint
CONFIG_ZMK_POINTING=y
CONFIG_I2C=y

### ZMK STUDIO
# MC: 2. zmk-studio test START
# https://github.com/zmkfirmware/zmk/blob/main/docs/docs/config/studio.md
#CONFIG_ZMK_STUDIO=y
#CONFIG_ZMK_STUDIO_LOCKING=n
# MC: zmk-studio test END
